name: CI workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-slim-chrome99-ff97
    steps:
      - uses: actions/checkout@v2

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn eslint 'src/**'

      - name: Run tests
        run: yarn test:ci

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
